WebApp/Models/Dto/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Utilities;

namespace WebApp.Models.Dto
{
    public class User
    {
        public class ValidUser
        {
            public Guid UserID { get; set; }

            public Guid OrganisationID { get; set; }

            public string FirstName { get; set; } 

            public string LastName { get; set; }

            public string PhoneNumber { get; set; }

            public string Email { get; set; } = "";

            public string Status { get; set; }

            public string message { get; set; }

            public APIError err { get; set; }
        }

        public class CreateUser
        {

            public string FirstName { get; set; }

            public string LastName { get; set; }

            public string PhoneNumber { get; set; }

            public string Email { get; set; }

            public string Password { get; set; }

            public string Status { get; set; }
        }

        public class ValidateUser
        {

            public string Email { get; set; }

            public string Password { get; set; }

        }


    }

}

WebApp/Controllers/OrganisationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Data.Services;
using WebApp.ViewModels;
using WebApp.Models.Dto;
using static WebApp.Models.Dto.MasterData;
using WebApp.WebManager;
using static WebApp.Models.Dto.Organisation;

namespace WebApp.Controllers
{
    public class OrganisationController : Controller
    {
        private readonly IMasterData masterdata;
        private readonly IOrganisationsvr org_registration;
        private readonly ISessionManager _sessionManager;
        private readonly IAccountsvr _accountsvr;

        public OrganisationController(IMasterData masterdata, IOrganisationsvr org_registration, ISessionManager _sessionManager, IAccountsvr _accountsvr)
        {
            this.masterdata = masterdata;
            this.org_registration = org_registration;
            this._sessionManager = _sessionManager;
            this._accountsvr = _accountsvr;
        }


        private View_Organisation.OrganisationObj MapToView(Organisation.Organisations dto)
        {
            var orgObj = new View_Organisation.OrganisationObj
            {

                Id = dto.Id,
                Legal_name = dto.Legal_name,
                Country = dto.CountryName,
                Currency =dto.CurrencyType,
                Industry = dto.Industry,
                AcceptTerms = dto.AcceptTerms
                

            };
            return orgObj;
        }

        public async Task<IActionResult> Index()
        {

            var dblstOrgs = await org_registration.GetOrganisationsAsyn();
            var dblstUnassignedOrgAccounts = await org_registration.GetUnAssignedAccountsAsyn();

            var SelectListData = await getSelectedListItemDataAsync();
            var lstOrgs = dblstOrgs.Select(MapToView).ToList();
            var vworg = new View_Organisation.OrganisationObj()
            {
                Orgs = lstOrgs,
                Countries = SelectListData[0],
                Currencies = SelectListData[1],
                AllUnAssignedAccounts = dblstUnassignedOrgAccounts
            };
            
            return View(vworg);

        }

        public async Task<IActionResult> Register() {

            var SelectListData = await getSelectedListItemDataAsync();

            var vworg = new View_Organisation.Create_Organisation()
            {
                
                Countries = SelectListData[0],
                Currencies = SelectListData[1]

            };

            _sessionManager.SaveSessionObject("Organization Registration", "page_title");

            return View(vworg);

            
        }

        public IActionResult Dashboard()
        {
            _sessionManager.SaveSessionObject("Organization Subcription Management", "page_title");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(View_Organisation.Create_Organisation vwOrg)
        {
            if (ModelState.IsValid)
            {
                var dto = new Organisation.CreateOrganisation
                {
                    Legal_name = vwOrg.Legal_name,
                    CountryName = vwOrg.Country,
                    CurrencyType = vwOrg.Currency,
                    Industry = vwOrg.Industry,
                    Business_Email = vwOrg.Business_email,
                    AcceptTerms = vwOrg.AcceptTerms
                    
                };

                var createdOrganisation = await org_registration.RegisterOrgnaisationAysnc(dto);

                if (createdOrganisation is null)
                {
                    var SelectListData = await getSelectedListItemDataAsync();

                    var vworg = new View_Organisation.Create_Organisation()
                    {

                        Countries = SelectListData[0],
                        Currencies = SelectListData[1]

                    };
                    ViewBag["Message"] = "An Error Occur Creating Organisation. Try again";
                    
                    return View(vworg);
                }

                    _sessionManager.SaveSessionObject(createdOrganisation.Id.ToString(), "tenantid");

            }

            await AssignOrganisationOwner();

            return RedirectToAction("Dashboard");

        }

        private async Task<bool> AssignOrganisationOwner()
        {
            
            var orgOwner = new AssignOganisationOwnerUser
            {

                OrganisationID = Guid.Parse(_sessionManager.GetSessionObject("tenantid")),
                UserID = Guid.Parse(_sessionManager.GetSessionObject("userid"))
            
            };

          var assignedUser =  await org_registration.AssignOrganisationOwnerAsyn(orgOwner);

            if (assignedUser != null)
            {
                return true;
            }
            return false;
        }

        private async Task<List<List<SelectListItem>>> getSelectedListItemDataAsync()
        {
            List<Country> countries = await masterdata.GetAllCountry();
            List<Currency> currencies = await masterdata.GetAllCurrency();

            var SelectlstCountry = countries.ToList().ConvertAll(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.Code
            });

            var SelectlstCurrency = currencies.ToList().ConvertAll(x => new SelectListItem
            {
                Text = x.Code + " - " + x.Description,
                Value = x.Code
            });

            var vworg = new View_Organisation.Create_Organisation()
            {

                Countries = SelectlstCountry,
                Currencies = SelectlstCurrency

            };

            var listSelectedItems = new List<List<SelectListItem>>
                {
                    SelectlstCountry,
                    SelectlstCurrency
                };


            return listSelectedItems;
        }
    }
}

WebApp/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Data.Services;
using WebApp.Models.Dto;
using WebApp.WebManager;
using static WebApp.ViewModels.Account;

namespace WebApp.Controllers
{
    
    public class UserController : Controller
    {
        private readonly IAccountsvr _accountsvr;
        private readonly ISessionManager _sessionManager;
        public UserController(IAccountsvr _accountsvr, ISessionManager _sessionManager)
        {
            this._accountsvr = _accountsvr;
            this._sessionManager = _sessionManager;
        }
        public IActionResult Index()
        {

            return View();

        }

        [HttpPost]
        public async Task<IActionResult> Index(Login vwLogin)
        {
            if (ModelState.IsValid)
            {
                var valLogin = new User.ValidateUser()
                {
                    Email = vwLogin.Email,
                    Password = vwLogin.Password
                };

                _sessionManager.SaveSessionObject(vwLogin.Email, "email");
                _sessionManager.SaveSessionObject(vwLogin.Password,"pwd");
                

                var validAccount = await _accountsvr.ValidateAccount(valLogin);

                if (validAccount != null && validAccount.Email.ToString() != "")
                {

                    var sessionValues = new Dictionary<string, string>
                    {
                        ["user"] = $"{validAccount.FirstName} {validAccount.LastName}",
                        ["page_title"] = "Dashboard",
                        ["userid"] = validAccount.UserID.ToString(),
                        ["organisationid"] = validAccount.OrganisationID.ToString()
                    };

                    foreach (var item in sessionValues)
                    {
                        _sessionManager.SaveSessionObject(item.Value, item.Key);
                    }

                    return RedirectToAction("Index","Home");

                }
                else
                {
                    if (validAccount.err == null)
                    {
                        ViewData["Message"] = validAccount.message;
                    }
                    else
                    {
                        ViewData["Message"] = validAccount.err.Message;
                    }
                    
                }

            }
            _sessionManager.ClearAllSession();
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }

        public IActionResult Welcome()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(Register nwAccount)
        {
            try { 
            
                if (ModelState.IsValid)
                {

                    var registeredUser = await _accountsvr.RegisterAccount(nwAccount);
                    if (registeredUser != null && registeredUser.Email != "")
                    {

                        var sessionValues = new Dictionary<string, string>
                        {
                            ["user"] = $"{nwAccount.First_name} {nwAccount.Last_name}",
                            ["page_title"] = string.Empty,
                            ["userid"] = registeredUser.UserID.ToString()
                        };

                        foreach (var item in sessionValues)
                        {
                            _sessionManager.SaveSessionObject(item.Value, item.Key);
                        }

                        return RedirectToAction("Welcome");
                        
                    }
                    ViewData["Message"] = registeredUser.err.Message;
                }
                
            }
            catch (Exception ex)
            {

            }
            
            return View();
        }

        public IActionResult LogOut()
        {
            return View();
        }
    }
}

WebApp/Views/User/Index.cshtml
@using WebApp.ViewModels;
@model Account.Login;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<div class="row justify-content-center">

    <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                    <div class="col-lg-6">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                            </div>


                            @{
            if (ViewData["Message"] is not null)
            {
                                <div class="alert alert-danger alert-dismissible fade show" role="alert">

                                    @ViewData["Message"]
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
            }
                            }



                            <form asp-action="Index" method="post">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="form-group">
                                    <input asp-for="Email" type="email" class="form-control form-control-user"
                                           id="exampleInputEmail" aria-describedby="emailHelp"
                                           placeholder="Enter Email Address...">
                                    <span asp-validation-for="Email" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <input asp-for="Password" type="password" class="form-control form-control-user"
                                           id="exampleInputPassword" placeholder="Password">
                                    <span asp-validation-for="Password" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <div class="custom-control custom-checkbox small">
                                        <input asp-for="RememberMe" type="checkbox" class="custom-control-input" id="customCheck">
                                        <label class="custom-control-label" for="customCheck">
                                            Remember
                                            Me
                                        </label>
                                        <span asp-validation-for="Password" class="text-danger"></span>
                                    </div>
                                </div>

                                @*<a href="index.html" class="btn btn-primary btn-user btn-block">
                Login
            </a>*@

                                <input type="submit" value="Login" class="btn btn-primary btn-user btn-block" />


                                <hr>
                                <a href="index.html" class="btn btn-google btn-user btn-block">
                                    <i class="fab fa-google fa-fw"></i> Login with Google
                                </a>
                                <a href="index.html" class="btn btn-facebook btn-user btn-block">
                                    <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
                                </a>
                            </form>
                            <hr>
                            <div class="text-center">
                                <a class="small" href="forgot-password.html">Forgot Password?</a>
                            </div>
                            <div class="text-center">
                                <a asp-controller="User" asp-action="Register" class="small">Create an Account!</a>
                                @*href="register.html"*@
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

WebApp/Views/User/Register.cshtml
@using WebApp.ViewModels
@model  Account.Register
@{
    ViewData["Title"] = "Register";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
            <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
            <div class="col-lg-7">
                <div class="p-5">
                    <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                    </div>


                    @{
                        if (ViewData["Message"] is not null)
                        {
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">

                                @ViewData["Message"]
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        }
                    }


                    <form asp-action="Register" method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                <input asp-for="First_name" type="text" class="form-control form-control-user" id="exampleFirstName"
                                       placeholder="First Name">
                                <span asp-validation-for="First_name" class="text-danger"></span>
                            </div>
                            <div class="col-sm-6">
                                <input asp-for="Last_name" type="text" class="form-control form-control-user" id="exampleLastName"
                                       placeholder="Last Name">
                                <span asp-validation-for="Last_name" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <input asp-for="Email" type="email" class="form-control form-control-user" id="exampleInputEmail"
                                   placeholder="Email Address">
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <input asp-for="Telephone" type="text" class="form-control form-control-user" id="exampleInputEmail"
                                   placeholder="Telephone Number">
                            <span asp-validation-for="Telephone" class="text-danger"></span>
                        </div>


                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                <input asp-for="Password" type="password" class="form-control form-control-user"
                                       id="exampleInputPassword" placeholder="Password">
                                <span asp-validation-for="Password" class="text-danger"></span>
                            </div>
                            <div class="col-sm-6">
                                <input asp-for="Comfirm_Password" type="password" class="form-control form-control-user"
                                       id="exampleRepeatPassword" placeholder="Repeat Password">
                                <span asp-validation-for="Comfirm_Password" class="text-danger"></span>
                            </div>
                        </div>
                        @*<a href="login.html" class="btn btn-primary btn-user btn-block">
                Register Account
            </a>*@

                        <input type="submit" value="Register Account" class="btn btn-facebook btn-user btn-block" />

                        <hr>
                        <a href="index.html" class="btn btn-google btn-user btn-block">
                            <i class="fab fa-google fa-fw"></i> Register with Google
                        </a>
                        <a href="index.html" class="btn btn-facebook btn-user btn-block">
                            <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
                        </a>

                    </form>

                    <hr>
                    <div class="text-center">
                        <a class="small" href="forgot-password.html">Forgot Password?</a>
                    </div>
                    <div class="text-center">
                        <a class="small" href="login.html">Already have an account? Login!</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebApp/Views/User/Welcome.cshtml
@using Microsoft.AspNetCore.Identity;
@using Microsoft.AspNetCore.Http;
@using System.Text;

@{
    ViewData["Title"] = "Welcome";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

@{

    byte[] bytes;
    bool isActive = Context.Session.TryGetValue("user", out bytes);

}

<div class="container text-center">

    <div class="row">


        <div class="col"></div>

        <div class="col-8">


            <div class="col-lg-auto mb-lg-5">


                @if (Context.Session.TryGetValue("user", out bytes))
                {
                <h1>Welcome, @Encoding.ASCII.GetString(bytes) 👋</h1>
                }
                else
                {
                <h1>Welcome !!! 👋</h1>
                }


                <p>Your account has been created successfully.</p>
                <hr />
                <p>
                    To continue, create a new organisation or join an existing one using an invitation.
                </p>

                <div class="actions">
                    <a asp-controller="Organisation" asp-action="Register" class="btn btn-primary btn-user btn-block">
                        Create a new organisation
                    </a>
                    <p></p>
                    <a href="/organisation/join" class="secondary-btn">
                        Join an organisation with an invite
                    </a>
                </div>
                <hr />

                @*<div class="footer">
            You’re one step away from accessing your dashboard.<br />
            Need help? <a href="/help">View setup guide</a>
        </div>*@

                <div>
                    You’re one step away from accessing your dashboard.<br />
                    Need help? <a href="/help">View setup guide</a>
                </div>


            </div>

        </div>

        <div class="col"></div>
    </div>
</div>